-o Game.t3

-DLANGUAGE=en_us
-DMESSAGESTYLE=neu
#-D TADS_INCLUDE_NET
-Fy obj -Fo obj
-o Game.t3
-lib system
-lib adv3/adv3

#-lib adv3/adv3web
#-lib webui
#lib/tadsnet.t


# Global Files
GameFiles/Contents/Lib_Contents.tl
GameFiles/Lib_Game.tl
GameFiles/Objects/Lib_Objects.tl
GameFiles/Weapons/Lib_Weapons.tl

# Achievements
GameFiles/Achievements/Lib_Achievements.tl

# Help Files
GameFiles/Help/Lib_Help.tl


# CHARACTERS
GameFiles/Characters/Lib_Characters.tl
# ENEMIES
GameFiles/Enemies/Lib_Enemies.tl

# SPAWNERS
GameFiles/Spawners/Lib_Spawners.tl


# LOCATIONS
GameFiles/Locations/Limbo.t

# BRIG
GameFiles/Locations/Brig/Lib_Brig.tl
GameFiles/Locations/Brig/Cell01/Lib_Brig_Cell01.tl
GameFiles/Locations/Brig/Cell02/Lib_Brig_Cell02.tl
GameFiles/Locations/Brig/Cell03/Lib_Brig_Cell03.tl
GameFiles/Locations/Brig/Cell04/Lib_Brig_Cell04.tl
GameFiles/Locations/Brig/HoldingCell/Lib_Brig_HoldingCell.tl
GameFiles/Locations/Brig/GuardPost/Lib_Brig_GuardPost.tl
GameFiles/Locations/Brig/Hall/Lib_Brig_Hall.tl

# MUNDANE HOLD
GameFiles/Locations/Hold_Mundane/Mundane_Hold_Access/Lib_Mundane_Hold_Access.tl
GameFiles/Locations/Hold_Mundane/Mundane_Hold_Port/Lib_Mundane_Hold_Port.tl
GameFiles/Locations/Hold_Mundane/Mundane_Hold_Starboard/Lib_Mundane_Hold_Starboard.tl

# HOLD
GameFiles/Locations/Hold/Hold_Access/Lib_Hold_Access.tl

# VENTILATION AFT
GameFiles/Locations/Ventilation_Aft/Lib_Ventilation_Aft.tl
GameFiles/Locations/Ventilation_Aft/MainPipe_Port/Lib_VntAft_MainPipe_Port.tl
GameFiles/Locations/Ventilation_Aft/PortFan/Lib_Ventilation_Aft_PortFan.tl
GameFiles/Locations/Ventilation_Aft/ForePortFan/Lib_Ventilation_Aft_ForePortFan.tl
GameFiles/Locations/Ventilation_Aft/ForeStarboardFan/Lib_Ventilation_Aft_ForeStarboardFan.tl
GameFiles/Locations/Ventilation_Aft/MainPipe_Starboard/Lib_VntAft_MainPipe_Starboard.tl
