name: The Guard Post

source: Brig_GuardPost.t


# Objects
source: Objects/GuardPost_Cabinet.t
source: Objects/GuardPost_Cabinet_Uniform.t
source: Objects/GuardPost_Chair.t
source: Objects/GuardPost_Closet.t
source: Objects/GuardPost_Closet_Cables.t
source: Objects/GuardPost_Closet_Cameras.t
source: Objects/GuardPost_Closet_CleaningSupplies.t
source: Objects/GuardPost_Desk.t
source: Objects/GuardPost_DeskChair.t
source: Objects/GuardPost_Monitor.t
