name: Mundane Hold Port

source: Mundane_Hold_Port.t
source: Mundane_Hold_Port_ForwardPortShelves.t
source: Mundane_Hold_Port_ForwardStarboardShelves.t
source: Mundane_Hold_Port_Aft.t


# Objects
source: Objects/Mundane_Hold_Port_Computer.t
source: Objects/Mundane_Hold_Port_ForwardPortShelves_Shelves.t
source: Objects/Mundane_Hold_Port_ForwardStarboardShelves_Shelves.t
source: Objects/Mundane_Hold_Port_AftShelves_01.t
source: Objects/Mundane_Hold_Port_AftShelves_02.t
